name: Security Checks

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/**"
  push:
    branches: [ "main" ]
    paths:
      - "server/**"

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------------------------------------------
      # Setup Ruby & Install Gems (Only needed for linting)
      # ------------------------------------------------------------
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
          working-directory: server

      # ------------------------------------------------------------
      # Brakeman for static analysis bad code / XSS / sql injections
      # ------------------------------------------------------------
      - name: Run Brakeman
        run: bundle exec brakeman -q -o brakeman-report.json -f json -w2 # -w flag is to control what warning lvls will trigger failure - now higher than medium

      # ------------------------------------------------------------
      # PUBLISH Brakeman report
      # ------------------------------------------------------------
      - name: Upload Brakeman report
        uses: actions/upload-artifact@v4
        with:
          name: brakeman-report
          path: server/brakeman-report.json

      # ------------------------------------------------------------
      # Bundle audit to check for dependency vulnerabilities
      # ------------------------------------------------------------
      - name: Run Bundler Audit
        run: bundle exec bundler-audit check --update --verbose | tee bundler-audit-report.txt

      # ------------------------------------------------------------
      # PUBLISH bundle audit report
      # ------------------------------------------------------------
      - name: Upload Bundler Audit report
        uses: actions/upload-artifact@v4
        with:
          name: bundler-audit-report
          path: server/bundler-audit-report.txt
