name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Set up Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#      - run: cd client && npm ci && npm run test -- --coverage

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Install Gems
        run: |
          cd munchora-server-relational-db
          bundle install --jobs 4 --retry 3

      - name: Run tests with coverage
        run: |
          cd munchora-server-relational-db
          bundle exec rspec
          ls -l coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        run: |
          cd munchora-server-relational-db
          sonar-scanner \
            -Dsonar.organization=munchora-test \
            -Dsonar.ruby.coverage.reportPaths=coverage/coverage.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}