name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Set up Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#      - run: cd client && npm ci && npm run test -- --coverage

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Install Gems
        run: |
          cd munchora-server-relational-db
          bundle add simplecov simplecov_json_formatter
      #   bundle install --jobs 4 --retry 3

      - name: Run tests with coverage
        run: |
          cd munchora-server-relational-db
          bundle exec rspec

      - name: Install Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH=$PATH:$PWD/sonar-scanner-4.8.0.2856-linux/bin

      - name: SonarQube Scan
        run: |
          cd munchora-server-relational-db
          sonar-scanner \
            -Dsonar.organization=munchora-test \
            -Dsonar.ruby.coverage.reportPaths=coverage/coverage.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}